name: Test-Build-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Static Site
        id: generate-static-site
        run: |
          ./scripts/gen-site.sh

      - name: Upload Static Site as an Artifact
        id: upload-static-site
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./gen/

  # github recommends doing the deployment as a separate job, not sure why

  deploy-job:
    runs-on: ubuntu-latest
    needs: build-job

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.upload-static-site.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy-to-github-pages
        uses: actions/deploy-pages@v4
